/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.grafandreas.datalang.CdlRuntimeModule;
import org.grafandreas.datalang.CdlStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CdlIdeSetup extends CdlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CdlRuntimeModule(), new CdlIdeModule()));
	}
	
}
