/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.check;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.grafandreas.datalang.check.CheckFactory
 * @model kind="package"
 * @generated
 */
public interface CheckPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "check";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.grafandreas.org/datalang/Check";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "check";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CheckPackage eINSTANCE = org.grafandreas.datalang.check.impl.CheckPackageImpl.init();

  /**
   * The meta object id for the '{@link org.grafandreas.datalang.check.impl.ChecksModelImpl <em>Checks Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.grafandreas.datalang.check.impl.ChecksModelImpl
   * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getChecksModel()
   * @generated
   */
  int CHECKS_MODEL = 0;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKS_MODEL__BLOCKS = 0;

  /**
   * The number of structural features of the '<em>Checks Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKS_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.grafandreas.datalang.check.impl.CheckBlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.grafandreas.datalang.check.impl.CheckBlockImpl
   * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getCheckBlock()
   * @generated
   */
  int CHECK_BLOCK = 1;

  /**
   * The feature id for the '<em><b>Req</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_BLOCK__REQ = 0;

  /**
   * The feature id for the '<em><b>Checks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_BLOCK__CHECKS = 1;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_BLOCK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.grafandreas.datalang.check.impl.ReqCheckImpl <em>Req Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.grafandreas.datalang.check.impl.ReqCheckImpl
   * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getReqCheck()
   * @generated
   */
  int REQ_CHECK = 2;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQ_CHECK__EXPR = 0;

  /**
   * The feature id for the '<em><b>Error Template</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQ_CHECK__ERROR_TEMPLATE = 1;

  /**
   * The feature id for the '<em><b>Attach To Fields</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQ_CHECK__ATTACH_TO_FIELDS = 2;

  /**
   * The number of structural features of the '<em>Req Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQ_CHECK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.grafandreas.datalang.check.impl.NamesImpl <em>Names</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.grafandreas.datalang.check.impl.NamesImpl
   * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getNames()
   * @generated
   */
  int NAMES = 3;

  /**
   * The feature id for the '<em><b>Attrs</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMES__ATTRS = 0;

  /**
   * The number of structural features of the '<em>Names</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.grafandreas.datalang.check.impl.ErrorTemplateImpl <em>Error Template</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.grafandreas.datalang.check.impl.ErrorTemplateImpl
   * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getErrorTemplate()
   * @generated
   */
  int ERROR_TEMPLATE = 4;

  /**
   * The feature id for the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_TEMPLATE__MESSAGE = 0;

  /**
   * The number of structural features of the '<em>Error Template</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_TEMPLATE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.grafandreas.datalang.check.ChecksModel <em>Checks Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checks Model</em>'.
   * @see org.grafandreas.datalang.check.ChecksModel
   * @generated
   */
  EClass getChecksModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.grafandreas.datalang.check.ChecksModel#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see org.grafandreas.datalang.check.ChecksModel#getBlocks()
   * @see #getChecksModel()
   * @generated
   */
  EReference getChecksModel_Blocks();

  /**
   * Returns the meta object for class '{@link org.grafandreas.datalang.check.CheckBlock <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see org.grafandreas.datalang.check.CheckBlock
   * @generated
   */
  EClass getCheckBlock();

  /**
   * Returns the meta object for the containment reference '{@link org.grafandreas.datalang.check.CheckBlock#getReq <em>Req</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Req</em>'.
   * @see org.grafandreas.datalang.check.CheckBlock#getReq()
   * @see #getCheckBlock()
   * @generated
   */
  EReference getCheckBlock_Req();

  /**
   * Returns the meta object for the containment reference list '{@link org.grafandreas.datalang.check.CheckBlock#getChecks <em>Checks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Checks</em>'.
   * @see org.grafandreas.datalang.check.CheckBlock#getChecks()
   * @see #getCheckBlock()
   * @generated
   */
  EReference getCheckBlock_Checks();

  /**
   * Returns the meta object for class '{@link org.grafandreas.datalang.check.ReqCheck <em>Req Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Req Check</em>'.
   * @see org.grafandreas.datalang.check.ReqCheck
   * @generated
   */
  EClass getReqCheck();

  /**
   * Returns the meta object for the containment reference '{@link org.grafandreas.datalang.check.ReqCheck#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.grafandreas.datalang.check.ReqCheck#getExpr()
   * @see #getReqCheck()
   * @generated
   */
  EReference getReqCheck_Expr();

  /**
   * Returns the meta object for the containment reference '{@link org.grafandreas.datalang.check.ReqCheck#getErrorTemplate <em>Error Template</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Error Template</em>'.
   * @see org.grafandreas.datalang.check.ReqCheck#getErrorTemplate()
   * @see #getReqCheck()
   * @generated
   */
  EReference getReqCheck_ErrorTemplate();

  /**
   * Returns the meta object for the containment reference '{@link org.grafandreas.datalang.check.ReqCheck#getAttachToFields <em>Attach To Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attach To Fields</em>'.
   * @see org.grafandreas.datalang.check.ReqCheck#getAttachToFields()
   * @see #getReqCheck()
   * @generated
   */
  EReference getReqCheck_AttachToFields();

  /**
   * Returns the meta object for class '{@link org.grafandreas.datalang.check.Names <em>Names</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Names</em>'.
   * @see org.grafandreas.datalang.check.Names
   * @generated
   */
  EClass getNames();

  /**
   * Returns the meta object for the reference list '{@link org.grafandreas.datalang.check.Names#getAttrs <em>Attrs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Attrs</em>'.
   * @see org.grafandreas.datalang.check.Names#getAttrs()
   * @see #getNames()
   * @generated
   */
  EReference getNames_Attrs();

  /**
   * Returns the meta object for class '{@link org.grafandreas.datalang.check.ErrorTemplate <em>Error Template</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Error Template</em>'.
   * @see org.grafandreas.datalang.check.ErrorTemplate
   * @generated
   */
  EClass getErrorTemplate();

  /**
   * Returns the meta object for the attribute '{@link org.grafandreas.datalang.check.ErrorTemplate#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message</em>'.
   * @see org.grafandreas.datalang.check.ErrorTemplate#getMessage()
   * @see #getErrorTemplate()
   * @generated
   */
  EAttribute getErrorTemplate_Message();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CheckFactory getCheckFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.grafandreas.datalang.check.impl.ChecksModelImpl <em>Checks Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.grafandreas.datalang.check.impl.ChecksModelImpl
     * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getChecksModel()
     * @generated
     */
    EClass CHECKS_MODEL = eINSTANCE.getChecksModel();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECKS_MODEL__BLOCKS = eINSTANCE.getChecksModel_Blocks();

    /**
     * The meta object literal for the '{@link org.grafandreas.datalang.check.impl.CheckBlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.grafandreas.datalang.check.impl.CheckBlockImpl
     * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getCheckBlock()
     * @generated
     */
    EClass CHECK_BLOCK = eINSTANCE.getCheckBlock();

    /**
     * The meta object literal for the '<em><b>Req</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK_BLOCK__REQ = eINSTANCE.getCheckBlock_Req();

    /**
     * The meta object literal for the '<em><b>Checks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK_BLOCK__CHECKS = eINSTANCE.getCheckBlock_Checks();

    /**
     * The meta object literal for the '{@link org.grafandreas.datalang.check.impl.ReqCheckImpl <em>Req Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.grafandreas.datalang.check.impl.ReqCheckImpl
     * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getReqCheck()
     * @generated
     */
    EClass REQ_CHECK = eINSTANCE.getReqCheck();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQ_CHECK__EXPR = eINSTANCE.getReqCheck_Expr();

    /**
     * The meta object literal for the '<em><b>Error Template</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQ_CHECK__ERROR_TEMPLATE = eINSTANCE.getReqCheck_ErrorTemplate();

    /**
     * The meta object literal for the '<em><b>Attach To Fields</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQ_CHECK__ATTACH_TO_FIELDS = eINSTANCE.getReqCheck_AttachToFields();

    /**
     * The meta object literal for the '{@link org.grafandreas.datalang.check.impl.NamesImpl <em>Names</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.grafandreas.datalang.check.impl.NamesImpl
     * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getNames()
     * @generated
     */
    EClass NAMES = eINSTANCE.getNames();

    /**
     * The meta object literal for the '<em><b>Attrs</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAMES__ATTRS = eINSTANCE.getNames_Attrs();

    /**
     * The meta object literal for the '{@link org.grafandreas.datalang.check.impl.ErrorTemplateImpl <em>Error Template</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.grafandreas.datalang.check.impl.ErrorTemplateImpl
     * @see org.grafandreas.datalang.check.impl.CheckPackageImpl#getErrorTemplate()
     * @generated
     */
    EClass ERROR_TEMPLATE = eINSTANCE.getErrorTemplate();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ERROR_TEMPLATE__MESSAGE = eINSTANCE.getErrorTemplate_Message();

  }

} //CheckPackage
