/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.check;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.grafandreas.datalang.check.CheckPackage
 * @generated
 */
public interface CheckFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CheckFactory eINSTANCE = org.grafandreas.datalang.check.impl.CheckFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Checks Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Checks Model</em>'.
   * @generated
   */
  ChecksModel createChecksModel();

  /**
   * Returns a new object of class '<em>Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Block</em>'.
   * @generated
   */
  CheckBlock createCheckBlock();

  /**
   * Returns a new object of class '<em>Req Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Req Check</em>'.
   * @generated
   */
  ReqCheck createReqCheck();

  /**
   * Returns a new object of class '<em>Names</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Names</em>'.
   * @generated
   */
  Names createNames();

  /**
   * Returns a new object of class '<em>Error Template</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Error Template</em>'.
   * @generated
   */
  ErrorTemplate createErrorTemplate();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CheckPackage getCheckPackage();

} //CheckFactory
