/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.check;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Checks Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.check.ChecksModel#getBlocks <em>Blocks</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.check.CheckPackage#getChecksModel()
 * @model
 * @generated
 */
public interface ChecksModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Blocks</b></em>' containment reference list.
   * The list contents are of type {@link org.grafandreas.datalang.check.CheckBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' containment reference list.
   * @see org.grafandreas.datalang.check.CheckPackage#getChecksModel_Blocks()
   * @model containment="true"
   * @generated
   */
  EList<CheckBlock> getBlocks();

} // ChecksModel
