/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.check;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.common.types.JvmParameterizedTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.check.CheckBlock#getReq <em>Req</em>}</li>
 *   <li>{@link org.grafandreas.datalang.check.CheckBlock#getChecks <em>Checks</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.check.CheckPackage#getCheckBlock()
 * @model
 * @generated
 */
public interface CheckBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Req</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req</em>' containment reference.
   * @see #setReq(JvmParameterizedTypeReference)
   * @see org.grafandreas.datalang.check.CheckPackage#getCheckBlock_Req()
   * @model containment="true"
   * @generated
   */
  JvmParameterizedTypeReference getReq();

  /**
   * Sets the value of the '{@link org.grafandreas.datalang.check.CheckBlock#getReq <em>Req</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Req</em>' containment reference.
   * @see #getReq()
   * @generated
   */
  void setReq(JvmParameterizedTypeReference value);

  /**
   * Returns the value of the '<em><b>Checks</b></em>' containment reference list.
   * The list contents are of type {@link org.grafandreas.datalang.check.ReqCheck}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Checks</em>' containment reference list.
   * @see org.grafandreas.datalang.check.CheckPackage#getCheckBlock_Checks()
   * @model containment="true"
   * @generated
   */
  EList<ReqCheck> getChecks();

} // CheckBlock
