/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.check;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.grafandreas.datalang.cdl.Attribute;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Names</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.check.Names#getAttrs <em>Attrs</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.check.CheckPackage#getNames()
 * @model
 * @generated
 */
public interface Names extends EObject
{
  /**
   * Returns the value of the '<em><b>Attrs</b></em>' reference list.
   * The list contents are of type {@link org.grafandreas.datalang.cdl.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attrs</em>' reference list.
   * @see org.grafandreas.datalang.check.CheckPackage#getNames_Attrs()
   * @model
   * @generated
   */
  EList<Attribute> getAttrs();

} // Names
