/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.grafandreas.datalang.csl.ui.internal.CslActivator;

public class CslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CslActivator.getInstance().getInjector("org.grafandreas.datalang.Csl");
	}

}
