/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.grafandreas.datalang.check.ui.internal.CheckActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CheckExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CheckActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CheckActivator activator = CheckActivator.getInstance();
		return activator != null ? activator.getInjector(CheckActivator.ORG_GRAFANDREAS_DATALANG_CHECK) : null;
	}

}
