/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CheckStandaloneSetup extends CheckStandaloneSetupGenerated {

	public static void doSetup() {
		new CheckStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
