/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.grafandreas.datalang.parser.antlr.internal.InternalCdlParser;
import org.grafandreas.datalang.services.CdlGrammarAccess;

public class CdlParser extends AbstractAntlrParser {

	@Inject
	private CdlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCdlParser createParser(XtextTokenStream stream) {
		return new InternalCdlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SpecificationModel";
	}

	public CdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
