/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.grafandreas.datalang.cdl.ui.internal.CdlActivator;

public class CdlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CdlActivator.getInstance().getInjector("org.grafandreas.datalang.Cdl");
	}

}
