/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CslUiModule extends AbstractCslUiModule {

	public CslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
