/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.grafandreas.datalang.CheckRuntimeModule;
import org.grafandreas.datalang.CheckStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CheckIdeSetup extends CheckStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CheckRuntimeModule(), new CheckIdeModule()));
	}
	
}
