/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.cdl;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.common.types.JvmTypeReference;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.cdl.Attribute#getType <em>Type</em>}</li>
 *   <li>{@link org.grafandreas.datalang.cdl.Attribute#getName <em>Name</em>}</li>
 *   <li>{@link org.grafandreas.datalang.cdl.Attribute#getLowerBound <em>Lower Bound</em>}</li>
 *   <li>{@link org.grafandreas.datalang.cdl.Attribute#getDeclaredUpperBound <em>Declared Upper Bound</em>}</li>
 *   <li>{@link org.grafandreas.datalang.cdl.Attribute#getDefaultExpr <em>Default Expr</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.cdl.CdlPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
	 * Returns the value of the '<em><b>Type</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Type</em>' containment reference.
	 * @see #setType(JvmTypeReference)
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getAttribute_Type()
	 * @model containment="true"
	 * @generated
	 */
  JvmTypeReference getType();

  /**
	 * Sets the value of the '{@link org.grafandreas.datalang.cdl.Attribute#getType <em>Type</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Type</em>' containment reference.
	 * @see #getType()
	 * @generated
	 */
  void setType(JvmTypeReference value);

  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getAttribute_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.grafandreas.datalang.cdl.Attribute#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Lower Bound</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Lower Bound</em>' attribute.
	 * @see #setLowerBound(int)
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getAttribute_LowerBound()
	 * @model
	 * @generated
	 */
  int getLowerBound();

  /**
	 * Sets the value of the '{@link org.grafandreas.datalang.cdl.Attribute#getLowerBound <em>Lower Bound</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Lower Bound</em>' attribute.
	 * @see #getLowerBound()
	 * @generated
	 */
  void setLowerBound(int value);

  /**
	 * Returns the value of the '<em><b>Declared Upper Bound</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Declared Upper Bound</em>' attribute.
	 * @see #setDeclaredUpperBound(int)
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getAttribute_DeclaredUpperBound()
	 * @model
	 * @generated
	 */
  int getDeclaredUpperBound();

  /**
	 * Sets the value of the '{@link org.grafandreas.datalang.cdl.Attribute#getDeclaredUpperBound <em>Declared Upper Bound</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Declared Upper Bound</em>' attribute.
	 * @see #getDeclaredUpperBound()
	 * @generated
	 */
  void setDeclaredUpperBound(int value);

  /**
	 * Returns the value of the '<em><b>Default Expr</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Default Expr</em>' containment reference.
	 * @see #setDefaultExpr(XExpression)
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getAttribute_DefaultExpr()
	 * @model containment="true"
	 * @generated
	 */
  XExpression getDefaultExpr();

  /**
	 * Sets the value of the '{@link org.grafandreas.datalang.cdl.Attribute#getDefaultExpr <em>Default Expr</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Default Expr</em>' containment reference.
	 * @see #getDefaultExpr()
	 * @generated
	 */
  void setDefaultExpr(XExpression value);

} // Attribute
