/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.cdl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.grafandreas.datalang.cdl.CdlFactory
 * @model kind="package"
 * @generated
 */
public interface CdlPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "cdl";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.grafandreas.org/datalang/Cdl";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "cdl";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  CdlPackage eINSTANCE = org.grafandreas.datalang.cdl.impl.CdlPackageImpl.init();

  /**
	 * The meta object id for the '{@link org.grafandreas.datalang.cdl.impl.SpecificationModelImpl <em>Specification Model</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.grafandreas.datalang.cdl.impl.SpecificationModelImpl
	 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getSpecificationModel()
	 * @generated
	 */
  int SPECIFICATION_MODEL = 0;

  /**
	 * The feature id for the '<em><b>Package</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SPECIFICATION_MODEL__PACKAGE = 0;

  /**
	 * The number of structural features of the '<em>Specification Model</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SPECIFICATION_MODEL_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.grafandreas.datalang.cdl.impl.PackageImpl <em>Package</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.grafandreas.datalang.cdl.impl.PackageImpl
	 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getPackage()
	 * @generated
	 */
  int PACKAGE = 1;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int PACKAGE__NAME = 0;

  /**
	 * The feature id for the '<em><b>Members</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int PACKAGE__MEMBERS = 1;

  /**
	 * The number of structural features of the '<em>Package</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int PACKAGE_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link org.grafandreas.datalang.cdl.impl.TypeImpl <em>Type</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.grafandreas.datalang.cdl.impl.TypeImpl
	 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getType()
	 * @generated
	 */
  int TYPE = 2;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TYPE__NAME = 0;

  /**
	 * The number of structural features of the '<em>Type</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TYPE_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.grafandreas.datalang.cdl.impl.RequirementTypeImpl <em>Requirement Type</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.grafandreas.datalang.cdl.impl.RequirementTypeImpl
	 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getRequirementType()
	 * @generated
	 */
  int REQUIREMENT_TYPE = 3;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int REQUIREMENT_TYPE__NAME = TYPE__NAME;

  /**
	 * The feature id for the '<em><b>General</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int REQUIREMENT_TYPE__GENERAL = TYPE_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Idfields</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int REQUIREMENT_TYPE__IDFIELDS = TYPE_FEATURE_COUNT + 1;

  /**
	 * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int REQUIREMENT_TYPE__ATTRIBUTES = TYPE_FEATURE_COUNT + 2;

  /**
	 * The number of structural features of the '<em>Requirement Type</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int REQUIREMENT_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 3;

  /**
	 * The meta object id for the '{@link org.grafandreas.datalang.cdl.impl.IDFieldImpl <em>ID Field</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.grafandreas.datalang.cdl.impl.IDFieldImpl
	 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getIDField()
	 * @generated
	 */
  int ID_FIELD = 4;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ID_FIELD__NAME = 0;

  /**
	 * The number of structural features of the '<em>ID Field</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ID_FIELD_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.grafandreas.datalang.cdl.impl.AttributeImpl <em>Attribute</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.grafandreas.datalang.cdl.impl.AttributeImpl
	 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getAttribute()
	 * @generated
	 */
  int ATTRIBUTE = 5;

  /**
	 * The feature id for the '<em><b>Type</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ATTRIBUTE__TYPE = 0;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ATTRIBUTE__NAME = 1;

  /**
	 * The feature id for the '<em><b>Lower Bound</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ATTRIBUTE__LOWER_BOUND = 2;

  /**
	 * The feature id for the '<em><b>Declared Upper Bound</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ATTRIBUTE__DECLARED_UPPER_BOUND = 3;

  /**
	 * The feature id for the '<em><b>Default Expr</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ATTRIBUTE__DEFAULT_EXPR = 4;

  /**
	 * The number of structural features of the '<em>Attribute</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ATTRIBUTE_FEATURE_COUNT = 5;

  /**
	 * The meta object id for the '{@link org.grafandreas.datalang.cdl.impl.EnumImpl <em>Enum</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.grafandreas.datalang.cdl.impl.EnumImpl
	 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getEnum()
	 * @generated
	 */
  int ENUM = 6;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENUM__NAME = TYPE__NAME;

  /**
	 * The feature id for the '<em><b>Literals</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENUM__LITERALS = TYPE_FEATURE_COUNT + 0;

  /**
	 * The number of structural features of the '<em>Enum</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENUM_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
	 * The meta object id for the '{@link org.grafandreas.datalang.cdl.impl.EnumLiteralImpl <em>Enum Literal</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.grafandreas.datalang.cdl.impl.EnumLiteralImpl
	 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getEnumLiteral()
	 * @generated
	 */
  int ENUM_LITERAL = 7;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENUM_LITERAL__NAME = 0;

  /**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENUM_LITERAL__VALUE = 1;

  /**
	 * The number of structural features of the '<em>Enum Literal</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENUM_LITERAL_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link org.grafandreas.datalang.cdl.impl.SimpleTypeImpl <em>Simple Type</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.grafandreas.datalang.cdl.impl.SimpleTypeImpl
	 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getSimpleType()
	 * @generated
	 */
  int SIMPLE_TYPE = 8;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SIMPLE_TYPE__NAME = TYPE__NAME;

  /**
	 * The feature id for the '<em><b>Lower Range Decimal</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SIMPLE_TYPE__LOWER_RANGE_DECIMAL = TYPE_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Lower Range Integer</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SIMPLE_TYPE__LOWER_RANGE_INTEGER = TYPE_FEATURE_COUNT + 1;

  /**
	 * The feature id for the '<em><b>Upper Range Decimal</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SIMPLE_TYPE__UPPER_RANGE_DECIMAL = TYPE_FEATURE_COUNT + 2;

  /**
	 * The feature id for the '<em><b>Upper Range Integer</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SIMPLE_TYPE__UPPER_RANGE_INTEGER = TYPE_FEATURE_COUNT + 3;

  /**
	 * The feature id for the '<em><b>Base Type</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SIMPLE_TYPE__BASE_TYPE = TYPE_FEATURE_COUNT + 4;

  /**
	 * The feature id for the '<em><b>Lower Bound</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SIMPLE_TYPE__LOWER_BOUND = TYPE_FEATURE_COUNT + 5;

  /**
	 * The feature id for the '<em><b>Declared Upper Bound</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SIMPLE_TYPE__DECLARED_UPPER_BOUND = TYPE_FEATURE_COUNT + 6;

  /**
	 * The number of structural features of the '<em>Simple Type</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SIMPLE_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 7;


  /**
	 * Returns the meta object for class '{@link org.grafandreas.datalang.cdl.SpecificationModel <em>Specification Model</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Specification Model</em>'.
	 * @see org.grafandreas.datalang.cdl.SpecificationModel
	 * @generated
	 */
  EClass getSpecificationModel();

  /**
	 * Returns the meta object for the containment reference list '{@link org.grafandreas.datalang.cdl.SpecificationModel#getPackage <em>Package</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Package</em>'.
	 * @see org.grafandreas.datalang.cdl.SpecificationModel#getPackage()
	 * @see #getSpecificationModel()
	 * @generated
	 */
  EReference getSpecificationModel_Package();

  /**
	 * Returns the meta object for class '{@link org.grafandreas.datalang.cdl.Package <em>Package</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Package</em>'.
	 * @see org.grafandreas.datalang.cdl.Package
	 * @generated
	 */
  EClass getPackage();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.Package#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.grafandreas.datalang.cdl.Package#getName()
	 * @see #getPackage()
	 * @generated
	 */
  EAttribute getPackage_Name();

  /**
	 * Returns the meta object for the containment reference list '{@link org.grafandreas.datalang.cdl.Package#getMembers <em>Members</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Members</em>'.
	 * @see org.grafandreas.datalang.cdl.Package#getMembers()
	 * @see #getPackage()
	 * @generated
	 */
  EReference getPackage_Members();

  /**
	 * Returns the meta object for class '{@link org.grafandreas.datalang.cdl.Type <em>Type</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Type</em>'.
	 * @see org.grafandreas.datalang.cdl.Type
	 * @generated
	 */
  EClass getType();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.Type#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.grafandreas.datalang.cdl.Type#getName()
	 * @see #getType()
	 * @generated
	 */
  EAttribute getType_Name();

  /**
	 * Returns the meta object for class '{@link org.grafandreas.datalang.cdl.RequirementType <em>Requirement Type</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Requirement Type</em>'.
	 * @see org.grafandreas.datalang.cdl.RequirementType
	 * @generated
	 */
  EClass getRequirementType();

  /**
	 * Returns the meta object for the containment reference '{@link org.grafandreas.datalang.cdl.RequirementType#getGeneral <em>General</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>General</em>'.
	 * @see org.grafandreas.datalang.cdl.RequirementType#getGeneral()
	 * @see #getRequirementType()
	 * @generated
	 */
  EReference getRequirementType_General();

  /**
	 * Returns the meta object for the containment reference list '{@link org.grafandreas.datalang.cdl.RequirementType#getIdfields <em>Idfields</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Idfields</em>'.
	 * @see org.grafandreas.datalang.cdl.RequirementType#getIdfields()
	 * @see #getRequirementType()
	 * @generated
	 */
  EReference getRequirementType_Idfields();

  /**
	 * Returns the meta object for the containment reference list '{@link org.grafandreas.datalang.cdl.RequirementType#getAttributes <em>Attributes</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Attributes</em>'.
	 * @see org.grafandreas.datalang.cdl.RequirementType#getAttributes()
	 * @see #getRequirementType()
	 * @generated
	 */
  EReference getRequirementType_Attributes();

  /**
	 * Returns the meta object for class '{@link org.grafandreas.datalang.cdl.IDField <em>ID Field</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>ID Field</em>'.
	 * @see org.grafandreas.datalang.cdl.IDField
	 * @generated
	 */
  EClass getIDField();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.IDField#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.grafandreas.datalang.cdl.IDField#getName()
	 * @see #getIDField()
	 * @generated
	 */
  EAttribute getIDField_Name();

  /**
	 * Returns the meta object for class '{@link org.grafandreas.datalang.cdl.Attribute <em>Attribute</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Attribute</em>'.
	 * @see org.grafandreas.datalang.cdl.Attribute
	 * @generated
	 */
  EClass getAttribute();

  /**
	 * Returns the meta object for the containment reference '{@link org.grafandreas.datalang.cdl.Attribute#getType <em>Type</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Type</em>'.
	 * @see org.grafandreas.datalang.cdl.Attribute#getType()
	 * @see #getAttribute()
	 * @generated
	 */
  EReference getAttribute_Type();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.Attribute#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.grafandreas.datalang.cdl.Attribute#getName()
	 * @see #getAttribute()
	 * @generated
	 */
  EAttribute getAttribute_Name();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.Attribute#getLowerBound <em>Lower Bound</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Lower Bound</em>'.
	 * @see org.grafandreas.datalang.cdl.Attribute#getLowerBound()
	 * @see #getAttribute()
	 * @generated
	 */
  EAttribute getAttribute_LowerBound();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.Attribute#getDeclaredUpperBound <em>Declared Upper Bound</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Declared Upper Bound</em>'.
	 * @see org.grafandreas.datalang.cdl.Attribute#getDeclaredUpperBound()
	 * @see #getAttribute()
	 * @generated
	 */
  EAttribute getAttribute_DeclaredUpperBound();

  /**
	 * Returns the meta object for the containment reference '{@link org.grafandreas.datalang.cdl.Attribute#getDefaultExpr <em>Default Expr</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Default Expr</em>'.
	 * @see org.grafandreas.datalang.cdl.Attribute#getDefaultExpr()
	 * @see #getAttribute()
	 * @generated
	 */
  EReference getAttribute_DefaultExpr();

  /**
	 * Returns the meta object for class '{@link org.grafandreas.datalang.cdl.Enum <em>Enum</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Enum</em>'.
	 * @see org.grafandreas.datalang.cdl.Enum
	 * @generated
	 */
  EClass getEnum();

  /**
	 * Returns the meta object for the containment reference list '{@link org.grafandreas.datalang.cdl.Enum#getLiterals <em>Literals</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Literals</em>'.
	 * @see org.grafandreas.datalang.cdl.Enum#getLiterals()
	 * @see #getEnum()
	 * @generated
	 */
  EReference getEnum_Literals();

  /**
	 * Returns the meta object for class '{@link org.grafandreas.datalang.cdl.EnumLiteral <em>Enum Literal</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Enum Literal</em>'.
	 * @see org.grafandreas.datalang.cdl.EnumLiteral
	 * @generated
	 */
  EClass getEnumLiteral();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.EnumLiteral#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.grafandreas.datalang.cdl.EnumLiteral#getName()
	 * @see #getEnumLiteral()
	 * @generated
	 */
  EAttribute getEnumLiteral_Name();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.EnumLiteral#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see org.grafandreas.datalang.cdl.EnumLiteral#getValue()
	 * @see #getEnumLiteral()
	 * @generated
	 */
  EAttribute getEnumLiteral_Value();

  /**
	 * Returns the meta object for class '{@link org.grafandreas.datalang.cdl.SimpleType <em>Simple Type</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Simple Type</em>'.
	 * @see org.grafandreas.datalang.cdl.SimpleType
	 * @generated
	 */
  EClass getSimpleType();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.SimpleType#getLowerRangeDecimal <em>Lower Range Decimal</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Lower Range Decimal</em>'.
	 * @see org.grafandreas.datalang.cdl.SimpleType#getLowerRangeDecimal()
	 * @see #getSimpleType()
	 * @generated
	 */
  EAttribute getSimpleType_LowerRangeDecimal();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.SimpleType#getLowerRangeInteger <em>Lower Range Integer</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Lower Range Integer</em>'.
	 * @see org.grafandreas.datalang.cdl.SimpleType#getLowerRangeInteger()
	 * @see #getSimpleType()
	 * @generated
	 */
  EAttribute getSimpleType_LowerRangeInteger();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.SimpleType#getUpperRangeDecimal <em>Upper Range Decimal</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Upper Range Decimal</em>'.
	 * @see org.grafandreas.datalang.cdl.SimpleType#getUpperRangeDecimal()
	 * @see #getSimpleType()
	 * @generated
	 */
  EAttribute getSimpleType_UpperRangeDecimal();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.SimpleType#getUpperRangeInteger <em>Upper Range Integer</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Upper Range Integer</em>'.
	 * @see org.grafandreas.datalang.cdl.SimpleType#getUpperRangeInteger()
	 * @see #getSimpleType()
	 * @generated
	 */
  EAttribute getSimpleType_UpperRangeInteger();

  /**
	 * Returns the meta object for the reference '{@link org.grafandreas.datalang.cdl.SimpleType#getBaseType <em>Base Type</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Base Type</em>'.
	 * @see org.grafandreas.datalang.cdl.SimpleType#getBaseType()
	 * @see #getSimpleType()
	 * @generated
	 */
  EReference getSimpleType_BaseType();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.SimpleType#getLowerBound <em>Lower Bound</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Lower Bound</em>'.
	 * @see org.grafandreas.datalang.cdl.SimpleType#getLowerBound()
	 * @see #getSimpleType()
	 * @generated
	 */
  EAttribute getSimpleType_LowerBound();

  /**
	 * Returns the meta object for the attribute '{@link org.grafandreas.datalang.cdl.SimpleType#getDeclaredUpperBound <em>Declared Upper Bound</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Declared Upper Bound</em>'.
	 * @see org.grafandreas.datalang.cdl.SimpleType#getDeclaredUpperBound()
	 * @see #getSimpleType()
	 * @generated
	 */
  EAttribute getSimpleType_DeclaredUpperBound();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  CdlFactory getCdlFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link org.grafandreas.datalang.cdl.impl.SpecificationModelImpl <em>Specification Model</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.grafandreas.datalang.cdl.impl.SpecificationModelImpl
		 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getSpecificationModel()
		 * @generated
		 */
    EClass SPECIFICATION_MODEL = eINSTANCE.getSpecificationModel();

    /**
		 * The meta object literal for the '<em><b>Package</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SPECIFICATION_MODEL__PACKAGE = eINSTANCE.getSpecificationModel_Package();

    /**
		 * The meta object literal for the '{@link org.grafandreas.datalang.cdl.impl.PackageImpl <em>Package</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.grafandreas.datalang.cdl.impl.PackageImpl
		 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getPackage()
		 * @generated
		 */
    EClass PACKAGE = eINSTANCE.getPackage();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute PACKAGE__NAME = eINSTANCE.getPackage_Name();

    /**
		 * The meta object literal for the '<em><b>Members</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference PACKAGE__MEMBERS = eINSTANCE.getPackage_Members();

    /**
		 * The meta object literal for the '{@link org.grafandreas.datalang.cdl.impl.TypeImpl <em>Type</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.grafandreas.datalang.cdl.impl.TypeImpl
		 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getType()
		 * @generated
		 */
    EClass TYPE = eINSTANCE.getType();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
		 * The meta object literal for the '{@link org.grafandreas.datalang.cdl.impl.RequirementTypeImpl <em>Requirement Type</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.grafandreas.datalang.cdl.impl.RequirementTypeImpl
		 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getRequirementType()
		 * @generated
		 */
    EClass REQUIREMENT_TYPE = eINSTANCE.getRequirementType();

    /**
		 * The meta object literal for the '<em><b>General</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference REQUIREMENT_TYPE__GENERAL = eINSTANCE.getRequirementType_General();

    /**
		 * The meta object literal for the '<em><b>Idfields</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference REQUIREMENT_TYPE__IDFIELDS = eINSTANCE.getRequirementType_Idfields();

    /**
		 * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference REQUIREMENT_TYPE__ATTRIBUTES = eINSTANCE.getRequirementType_Attributes();

    /**
		 * The meta object literal for the '{@link org.grafandreas.datalang.cdl.impl.IDFieldImpl <em>ID Field</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.grafandreas.datalang.cdl.impl.IDFieldImpl
		 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getIDField()
		 * @generated
		 */
    EClass ID_FIELD = eINSTANCE.getIDField();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ID_FIELD__NAME = eINSTANCE.getIDField_Name();

    /**
		 * The meta object literal for the '{@link org.grafandreas.datalang.cdl.impl.AttributeImpl <em>Attribute</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.grafandreas.datalang.cdl.impl.AttributeImpl
		 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getAttribute()
		 * @generated
		 */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
		 * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
		 * The meta object literal for the '<em><b>Lower Bound</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ATTRIBUTE__LOWER_BOUND = eINSTANCE.getAttribute_LowerBound();

    /**
		 * The meta object literal for the '<em><b>Declared Upper Bound</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ATTRIBUTE__DECLARED_UPPER_BOUND = eINSTANCE.getAttribute_DeclaredUpperBound();

    /**
		 * The meta object literal for the '<em><b>Default Expr</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ATTRIBUTE__DEFAULT_EXPR = eINSTANCE.getAttribute_DefaultExpr();

    /**
		 * The meta object literal for the '{@link org.grafandreas.datalang.cdl.impl.EnumImpl <em>Enum</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.grafandreas.datalang.cdl.impl.EnumImpl
		 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getEnum()
		 * @generated
		 */
    EClass ENUM = eINSTANCE.getEnum();

    /**
		 * The meta object literal for the '<em><b>Literals</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ENUM__LITERALS = eINSTANCE.getEnum_Literals();

    /**
		 * The meta object literal for the '{@link org.grafandreas.datalang.cdl.impl.EnumLiteralImpl <em>Enum Literal</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.grafandreas.datalang.cdl.impl.EnumLiteralImpl
		 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getEnumLiteral()
		 * @generated
		 */
    EClass ENUM_LITERAL = eINSTANCE.getEnumLiteral();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ENUM_LITERAL__NAME = eINSTANCE.getEnumLiteral_Name();

    /**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute ENUM_LITERAL__VALUE = eINSTANCE.getEnumLiteral_Value();

    /**
		 * The meta object literal for the '{@link org.grafandreas.datalang.cdl.impl.SimpleTypeImpl <em>Simple Type</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.grafandreas.datalang.cdl.impl.SimpleTypeImpl
		 * @see org.grafandreas.datalang.cdl.impl.CdlPackageImpl#getSimpleType()
		 * @generated
		 */
    EClass SIMPLE_TYPE = eINSTANCE.getSimpleType();

    /**
		 * The meta object literal for the '<em><b>Lower Range Decimal</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute SIMPLE_TYPE__LOWER_RANGE_DECIMAL = eINSTANCE.getSimpleType_LowerRangeDecimal();

    /**
		 * The meta object literal for the '<em><b>Lower Range Integer</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute SIMPLE_TYPE__LOWER_RANGE_INTEGER = eINSTANCE.getSimpleType_LowerRangeInteger();

    /**
		 * The meta object literal for the '<em><b>Upper Range Decimal</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute SIMPLE_TYPE__UPPER_RANGE_DECIMAL = eINSTANCE.getSimpleType_UpperRangeDecimal();

    /**
		 * The meta object literal for the '<em><b>Upper Range Integer</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute SIMPLE_TYPE__UPPER_RANGE_INTEGER = eINSTANCE.getSimpleType_UpperRangeInteger();

    /**
		 * The meta object literal for the '<em><b>Base Type</b></em>' reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SIMPLE_TYPE__BASE_TYPE = eINSTANCE.getSimpleType_BaseType();

    /**
		 * The meta object literal for the '<em><b>Lower Bound</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute SIMPLE_TYPE__LOWER_BOUND = eINSTANCE.getSimpleType_LowerBound();

    /**
		 * The meta object literal for the '<em><b>Declared Upper Bound</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute SIMPLE_TYPE__DECLARED_UPPER_BOUND = eINSTANCE.getSimpleType_DeclaredUpperBound();

  }

} //CdlPackage
