/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.cdl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.cdl.Enum#getLiterals <em>Literals</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.cdl.CdlPackage#getEnum()
 * @model
 * @generated
 */
public interface Enum extends Type
{
  /**
	 * Returns the value of the '<em><b>Literals</b></em>' containment reference list.
	 * The list contents are of type {@link org.grafandreas.datalang.cdl.EnumLiteral}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Literals</em>' containment reference list.
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getEnum_Literals()
	 * @model containment="true"
	 * @generated
	 */
  EList<EnumLiteral> getLiterals();

} // Enum
