/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.cdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.cdl.Package#getName <em>Name</em>}</li>
 *   <li>{@link org.grafandreas.datalang.cdl.Package#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.cdl.CdlPackage#getPackage()
 * @model
 * @generated
 */
public interface Package extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getPackage_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.grafandreas.datalang.cdl.Package#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Members</b></em>' containment reference list.
	 * The list contents are of type {@link org.grafandreas.datalang.cdl.Type}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Members</em>' containment reference list.
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getPackage_Members()
	 * @model containment="true"
	 * @generated
	 */
  EList<Type> getMembers();

} // Package
