/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.cdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmParameterizedTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requirement Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.cdl.RequirementType#getGeneral <em>General</em>}</li>
 *   <li>{@link org.grafandreas.datalang.cdl.RequirementType#getIdfields <em>Idfields</em>}</li>
 *   <li>{@link org.grafandreas.datalang.cdl.RequirementType#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.cdl.CdlPackage#getRequirementType()
 * @model
 * @generated
 */
public interface RequirementType extends Type
{
  /**
	 * Returns the value of the '<em><b>General</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>General</em>' containment reference.
	 * @see #setGeneral(JvmParameterizedTypeReference)
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getRequirementType_General()
	 * @model containment="true"
	 * @generated
	 */
  JvmParameterizedTypeReference getGeneral();

  /**
	 * Sets the value of the '{@link org.grafandreas.datalang.cdl.RequirementType#getGeneral <em>General</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>General</em>' containment reference.
	 * @see #getGeneral()
	 * @generated
	 */
  void setGeneral(JvmParameterizedTypeReference value);

  /**
	 * Returns the value of the '<em><b>Idfields</b></em>' containment reference list.
	 * The list contents are of type {@link org.grafandreas.datalang.cdl.IDField}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Idfields</em>' containment reference list.
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getRequirementType_Idfields()
	 * @model containment="true"
	 * @generated
	 */
  EList<IDField> getIdfields();

  /**
	 * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
	 * The list contents are of type {@link org.grafandreas.datalang.cdl.Attribute}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Attributes</em>' containment reference list.
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getRequirementType_Attributes()
	 * @model containment="true"
	 * @generated
	 */
  EList<Attribute> getAttributes();

} // RequirementType
