/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.cdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Specification Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.cdl.SpecificationModel#getPackage <em>Package</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.cdl.CdlPackage#getSpecificationModel()
 * @model
 * @generated
 */
public interface SpecificationModel extends EObject
{
  /**
	 * Returns the value of the '<em><b>Package</b></em>' containment reference list.
	 * The list contents are of type {@link org.grafandreas.datalang.cdl.Package}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Package</em>' containment reference list.
	 * @see org.grafandreas.datalang.cdl.CdlPackage#getSpecificationModel_Package()
	 * @model containment="true"
	 * @generated
	 */
  EList<org.grafandreas.datalang.cdl.Package> getPackage();

} // SpecificationModel
