/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.grafandreas.datalang.parser.antlr.internal.InternalCheckParser;
import org.grafandreas.datalang.services.CheckGrammarAccess;

public class CheckParser extends AbstractAntlrParser {

	@Inject
	private CheckGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCheckParser createParser(XtextTokenStream stream) {
		return new InternalCheckParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ChecksModel";
	}

	public CheckGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CheckGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
