/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.grafandreas.datalang.check.ui.internal.CheckActivator;

public class CheckUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CheckActivator.getInstance().getInjector("org.grafandreas.datalang.Check");
	}

}
