/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.grafandreas.datalang.cdl.ui.internal.CdlActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CdlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CdlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CdlActivator activator = CdlActivator.getInstance();
		return activator != null ? activator.getInjector(CdlActivator.ORG_GRAFANDREAS_DATALANG_CDL) : null;
	}

}
