/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.grafandreas.datalang.parser.antlr.internal.InternalCslParser;
import org.grafandreas.datalang.services.CslGrammarAccess;

public class CslParser extends AbstractAntlrParser {

	@Inject
	private CslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCslParser createParser(XtextTokenStream stream) {
		return new InternalCslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Instances";
	}

	public CslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
