/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractCheckScopeProvider extends XbaseBatchScopeProvider {
}
