/*
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.grafandreas.datalang.csl.ui.internal.CslActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CslActivator activator = CslActivator.getInstance();
		return activator != null ? activator.getInjector(CslActivator.ORG_GRAFANDREAS_DATALANG_CSL) : null;
	}

}
