/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.csl;

import org.eclipse.emf.ecore.EObject;

import org.grafandreas.datalang.cdl.IDField;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ID Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.csl.IDAssignment#getDeclaration <em>Declaration</em>}</li>
 *   <li>{@link org.grafandreas.datalang.csl.IDAssignment#getIdSpec <em>Id Spec</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.csl.CslPackage#getIDAssignment()
 * @model
 * @generated
 */
public interface IDAssignment extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaration</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' reference.
   * @see #setDeclaration(IDField)
   * @see org.grafandreas.datalang.csl.CslPackage#getIDAssignment_Declaration()
   * @model
   * @generated
   */
  IDField getDeclaration();

  /**
   * Sets the value of the '{@link org.grafandreas.datalang.csl.IDAssignment#getDeclaration <em>Declaration</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(IDField value);

  /**
   * Returns the value of the '<em><b>Id Spec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id Spec</em>' attribute.
   * @see #setIdSpec(String)
   * @see org.grafandreas.datalang.csl.CslPackage#getIDAssignment_IdSpec()
   * @model
   * @generated
   */
  String getIdSpec();

  /**
   * Sets the value of the '{@link org.grafandreas.datalang.csl.IDAssignment#getIdSpec <em>Id Spec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id Spec</em>' attribute.
   * @see #getIdSpec()
   * @generated
   */
  void setIdSpec(String value);

} // IDAssignment
