/**
 * generated by Xtext 2.25.0
 */
package org.grafandreas.datalang.csl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instances</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.grafandreas.datalang.csl.Instances#getName <em>Name</em>}</li>
 *   <li>{@link org.grafandreas.datalang.csl.Instances#getInstances <em>Instances</em>}</li>
 * </ul>
 *
 * @see org.grafandreas.datalang.csl.CslPackage#getInstances()
 * @model
 * @generated
 */
public interface Instances extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.grafandreas.datalang.csl.CslPackage#getInstances_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.grafandreas.datalang.csl.Instances#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Instances</b></em>' containment reference list.
   * The list contents are of type {@link org.grafandreas.datalang.csl.Instance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instances</em>' containment reference list.
   * @see org.grafandreas.datalang.csl.CslPackage#getInstances_Instances()
   * @model containment="true"
   * @generated
   */
  EList<Instance> getInstances();

} // Instances
